version: '3.9'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
    - $HOME/neo4j/import:/var/lib/neo4j/import
    - $HOME/neo4j/conf:/var/lib/neo4j/conf
    - $HOME/neo4j/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687